### ISSUE TITLE
 Unused varaibles

### ISSUE THREAD

**Issue by andreypz** [ResonantHbbHgg/bbggTools#1]
Need to comment out all unused variables in bbggTools/src/bbgg2DFitter.cc

**Comment by rateixei** [comment]
For laziness, we just use "./Compile.sh" instead of "scramv1 b". Which adds the flags to ignore all the unused variables.
Those variables are not really unused, they are used for memory handling things in the workspaces, I believe.

**Comment by andreypz** [comment]
Yes, I use this Compile file. Still, this is strange, we need  to fix it.

My use case is that I compile the bbggTools together with my own code in
order to use the ID functions. It is inconvenient and annoying to have
those errors/warnings.

By the way, could you add me to the git group with commit permissions,
please.
I'd like to edit something, so that it compiles with my code.

**Comment by OlivierBondu** [comment]
@andreypz : I just added you to the organization members
I tend to agree with you warnings should be cleaned up... we're likely to build on this starting block, so we'll get more warnings, and we may miss some important ones...

(also for the Limit_code repo: I would migrate all root .C macros to compiled code...)

as for git/github handling: I would advocate to have any change to the code go through a pull request from one's fork of the repository.... but I won't be trying to enforce that any longer, it's just a suggestion ;)

**Comment by rateixei** [comment]
I agree that these errors should be cleaned up. The flags were a matter of quickly patching the problem to get the limit code working.
However, the solution is not as simple as commenting those variables. As noted, they are used in some places.

I agree with @OlivierBondu regarding pull requests.

**Comment by flagarde** [comment]
Hi, 

I supress a lot of warnings in the beta branch... 
But I did change in the program which i know are ugly .. I have to change some part of the program 

François 


----- Mail original -----

De: "Rafael Teixeira de Lima" <notifications@github.com> 
À: "ResonantHbbHgg/bbggTools" <bbggTools@noreply.github.com> 
Envoyé: Mardi 1 Décembre 2015 17:34:38 
Objet: Re: [bbggTools] Unused varaibles (#1) 



I agree that these errors should be cleaned up. The flags were a matter of quickly patching the problem to get the limit code working. 
However, the solution is not as simple as commenting those variables. As noted, they are used in some places. 

I agree with @OlivierBondu regarding pull requests.

**Comment by andreypz** [comment]
This seems to be finally fixed. Thanks to Rafael.
