### ISSUE TITLE
Misleading varaible names

### ISSUE THREAD

**Issue by andreypz** [ResonantHbbHgg/bbggTools#21]
We need to change some variable names here:
https://github.com/ResonantHbbHgg/bbggTools/blob/master/src/bbggJetRegression.cc#L97-L98
They are misleading because H means hadronic, Em - electromagnetic, but in those variables the names are mixed.

**Comment by OlivierBondu** [comment]
I think this follows whatever is provided in the regression xml... this should be requested upstream first ?
